# docker-compose.local.yml

version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
    depends_on:
      - mongodb
    environment:
      MONGODB_URI: "mongodb://mongodb:27017/bookstore_bastan"
  mongodb:
    image: 'mongo:latest'
    ports:
      - '27017:27017'